/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *  http://aws.amazon.com/apache2.0
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

package software.amazon.glue.s3a.resolver;

public enum S3Request {
  AbortMultipartUploadRequest,
  CompleteMultipartUploadRequest,
  CopyObjectRequest,
  CreateBucketRequest,
  CreateMultipartUploadRequest,
  CreateSessionRequest,
  DeleteBucketAnalyticsConfigurationRequest,
  DeleteBucketCorsRequest,
  DeleteBucketEncryptionRequest,
  DeleteBucketIntelligentTieringConfigurationRequest,
  DeleteBucketInventoryConfigurationRequest,
  DeleteBucketLifecycleRequest,
  DeleteBucketMetricsConfigurationRequest,
  DeleteBucketOwnershipControlsRequest,
  DeleteBucketPolicyRequest,
  DeleteBucketReplicationRequest,
  DeleteBucketRequest,
  DeleteBucketTaggingRequest,
  DeleteBucketWebsiteRequest,
  DeleteObjectRequest,
  DeleteObjectTaggingRequest,
  DeleteObjectsRequest,
  DeletePublicAccessBlockRequest,
  GetBucketAccelerateConfigurationRequest,
  GetBucketAclRequest,
  GetBucketAnalyticsConfigurationRequest,
  GetBucketCorsRequest,
  GetBucketEncryptionRequest,
  GetBucketIntelligentTieringConfigurationRequest,
  GetBucketInventoryConfigurationRequest,
  GetBucketLifecycleConfigurationRequest,
  GetBucketLocationRequest,
  GetBucketLoggingRequest,
  GetBucketMetricsConfigurationRequest,
  GetBucketNotificationConfigurationRequest,
  GetBucketOwnershipControlsRequest,
  GetBucketPolicyRequest,
  GetBucketPolicyStatusRequest,
  GetBucketReplicationRequest,
  GetBucketRequestPaymentRequest,
  GetBucketTaggingRequest,
  GetBucketVersioningRequest,
  GetBucketWebsiteRequest,
  GetObjectAclRequest,
  GetObjectAttributesRequest,
  GetObjectLegalHoldRequest,
  GetObjectLockConfigurationRequest,
  GetObjectRequest,
  GetObjectRetentionRequest,
  GetObjectTaggingRequest,
  GetObjectTorrentRequest,
  GetPublicAccessBlockRequest,
  HeadBucketRequest,
  HeadObjectRequest,
  ListBucketAnalyticsConfigurationsRequest,
  ListBucketIntelligentTieringConfigurationsRequest,
  ListBucketInventoryConfigurationsRequest,
  ListBucketMetricsConfigurationsRequest,
  ListBucketsRequest,
  ListDirectoryBucketsRequest,
  ListMultipartUploadsRequest,
  ListObjectVersionsRequest,
  ListObjectsRequest,
  ListObjectsV2Request,
  ListPartsRequest,
  PutBucketAccelerateConfigurationRequest,
  PutBucketAclRequest,
  PutBucketAnalyticsConfigurationRequest,
  PutBucketCorsRequest,
  PutBucketEncryptionRequest,
  PutBucketIntelligentTieringConfigurationRequest,
  PutBucketInventoryConfigurationRequest,
  PutBucketLifecycleConfigurationRequest,
  PutBucketLoggingRequest,
  PutBucketMetricsConfigurationRequest,
  PutBucketNotificationConfigurationRequest,
  PutBucketOwnershipControlsRequest,
  PutBucketPolicyRequest,
  PutBucketReplicationRequest,
  PutBucketRequestPaymentRequest,
  PutBucketTaggingRequest,
  PutBucketVersioningRequest,
  PutBucketWebsiteRequest,
  PutObjectAclRequest,
  PutObjectLegalHoldRequest,
  PutObjectLockConfigurationRequest,
  PutObjectRequest,
  PutObjectRetentionRequest,
  PutObjectTaggingRequest,
  PutPublicAccessBlockRequest,
  RestoreObjectRequest,
  SelectObjectContentRequest,
  UploadPartCopyRequest,
  UploadPartRequest,
  WriteGetObjectResponseRequest,
}
